<header>
            <img src="images/visitvictoria.png" alt="visitvictoria">
        
            <nav class="subheading">
                <ul class="subheading">
                    <li><a class="home" href="index.php">Home</a></li>
                    <li><a class="insert" href="insert.php">Insert</a></li>
                    <li><a class="modify" href="modify.php">Modify</a></li>
                    <li><a class="contact" href="contact.php">Contact Us</a></li>
                </ul>
            </nav>
    </header>